version: '3.8'  

services:  
  db:  
    image: postgres:13  
    restart: always  
    environment:  
      POSTGRES_USER: user  
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: webshop  
    volumes:  
      - postgres_data:/var/lib/postgresql/data  
    ports:  
      - "5432:5432"  

  backend:  
    build:  
      context: ./backend  
      dockerfile: Dockerfile  
    restart: always  
    environment:  
      DB_HOST: db  
      DB_PORT: 5432  
      DB_USER: user  
      DB_PASSWORD: password  
      DB_NAME: webshop  
      PORT: 5000  
    ports:  
      - "5000:5000"  
    depends_on:  
      - db  

  frontend:  
    build:  
      context: ./frontend  
      dockerfile: Dockerfile  
    restart: always  
    ports:  
      - "3000:3000"  

volumes:  
  postgres_data:  