version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: webshop-db
    environment:
      - POSTGRES_DB=webshop
      - POSTGRES_USER=webshop_user
      - POSTGRES_PASSWORD=webshop_password
    ports:
      - "5432:5432"  # Exposes the PostgreSQL service on port 5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize the database with init.sql
    networks:
      - webshop_network

networks:
  webshop_network:
    driver: bridge